In [175]:
from sklearn.metrics import accuracy_score
import numpy as np
import tensorflow as tf
import json
import scipy.io
import matplotlib.pyplot as plt
from PIL import Image, ImageDraw
import cv2
import h5py
import scipy.io

plt.rcParams["figure.figsize"] = 8,8

In [176]:
from scipy.signal import find_peaks
def spike_finder(traces, max_t=0.4, distance=3):
    spikes_all = []
    for trace in traces:
        maximum = np.max(np.array(trace))
        min_height = max_t * maximum
        spikes = find_peaks(x=trace, height=min_height, distance=distance)
        spikes_all.append(spikes[0].tolist())
        
    return spikes_all

In [177]:
def load_ground_truth_generation_data(path, gui=False):
    """
    Loads ground truth data generated by MATLAB annotation tool.

    Returns:
        filters_binary 
        600 x 500 x 500 bool

        events_in_frames 
        11998 x {eventsInThisFrame} int

        events_for_filters 
        600 x {eventsForThisFilter} intfor i in range(contours_all.shape[0]):

    coord = []
    for j in range(len(contours_all[i][0])):

        y = contours_all[i][0][j][0][1]
        x = contours_all[i][0][j][0][0]
        coord.append([x,y])

    coord.append(coord[0])
    coords_all_pca.append(coord)

    xs, ys = zip(*coord)
    plt.plot(xs,ys, c=plt.get_cmap('autumn')(i/contours_all.shape[0]))
fig = plt.gcf()
plt.show()

        filter_centroids
        600 x 2 int
    """
    ground_truth_generation_data = scipy.io.loadmat(path)

    # 600 x 500 x 500 bool
    filters_binary = ground_truth_generation_data["filtersBinary"]
    filters_binary = np.array(
        [
            np.array(filters_binary[:, :, i]).transpose()
            for i in range(np.shape(filters_binary)[2])
        ],
        dtype=np.bool,
    )

    # 11998 x {eventsInThisFrame} int
    events_in_frames = ground_truth_generation_data["eventsInFrames"]

    if not gui:
        events_in_frames = np.array(
            [events_in_frames[0, i][0] - 1 for i in range(np.shape(events_in_frames)[1])]
        )

    else:
        
        events_in_frames_new = []
        for event in events_in_frames[0]:
            if np.array(event).size == 0:
                events_in_frames_new.append(np.array([]))
            else:
            
                events_in_frames_new.append(np.array(event[0]))
        events_in_frames = np.array(events_in_frames_new)
        
        
    # 600 x {eventsForThisFilter} int
    events_for_filters = ground_truth_generation_data["eventsForFilters"]

    if not gui:
        events_for_filters = np.array(
            [
                events_for_filters[0, i][0] - 1
                for i in range(np.shape(events_for_filters)[1])
            ]
        )
    else:
        events_for_filters_new = []
        for event in events_for_filters[0]:
            if np.array(event).size == 0:
                events_for_filters_new.append(np.array([]))
            else:
            
                events_for_filters_new.append(np.array(event[0]))
        print(events_for_filters_new[0][0])
        events_for_filters = np.array(events_for_filters_new)

    # 600 x 2 int
    filter_centroids = ground_truth_generation_data["filterCentroids"]
    filter_centroids = [[y, x] for [x, y] in filter_centroids]
    return [filters_binary, events_for_filters, filter_centroids, events_in_frames]

In [178]:
def find_centroids_from_binary_mask(mask):
    
    #float_img = float(mask)
    img = np.array(mask * 255, dtype = np.uint8)



    # convert the grayscale image to binary image
    ret,thresh = cv2.threshold(img,127,255,0)

    # calculate moments of binary image
    M = cv2.moments(thresh)

    # calculate x,y coordinate of center
    cX = int(M["m10"] / M["m00"])
    cY = int(M["m01"] / M["m00"])
    
    return cX, cY


In [179]:
def binary_mask_from_contour(coords):
    
    width = 500
    height = 500
    
    polygon = [tuple(x) for x in coords]

    img = Image.new('L', (width, height), 0)
    ImageDraw.Draw(img).polygon(polygon, outline=1, fill=1)
    mask = np.array(img)
    return mask

In [180]:
def load_preprocessed_movie(movie_path):
    movie = h5py.File(movie_path, 'r')
    movie = movie['1']
    return movie

In [210]:
#we wanna look like this
pca_ica_w = scipy.io.loadmat("/home/user/Documents/single_session/dataPackedForGeneration.mat")
eventsForFilters = pca_ica_w["eventsForFilters"]
eventsInFrames = pca_ica_w["eventsInFrames"]
filterCentroids = pca_ica_w["filterCentroids"]
filtersBinary = pca_ica_w['filtersBinary']

# #load gui mat
#gui_mat = scipy.io.loadmat('/home/user/Documents/single_session/GUI/synthetic/gui_extracted_wo_added.mat')
gui_mat = scipy.io.loadmat('/home/user/Documents/single_session/GUI/singleshot/gui_extracted.mat')
coords_gui = gui_mat["coordinates"][0]
events = gui_mat['events'][0]
traces = gui_mat['traces']
#load movie belonging to gui data
#movie_path = '/home/user/Documents/synthetic_datasets/sequence_9/video/movie.h5'
movie_path = '/home/user/Documents/single_session/preprocessed/preprocessedMovie.h5'
movie = load_preprocessed_movie(movie_path)







# events_cnmfe_added = spike_finder(traces[340:len(traces)])
# events_cnmfe= np.array([np.array(x) for x in events_cnmfe_added])

    

# events_new = []
# for event in events[0:340]:
#     events_new.append(event)
# for event in events_cnmfe:
#     events_new.append([event])
# events_new = np.array(events_new)

events_new = events
# filters binary
masks_gui = []
for coord in coords_gui:
    mask = binary_mask_from_contour(coord.tolist())
    masks_gui.append(mask)

masks_gui = np.array(masks_gui)
filtersBinaryGUI = np.transpose(masks_gui, (1, 2, 0))



# eventsForFiltersGUI
eventsForFiltersGUI = []
for i, event in enumerate(events_new):
    if not list(event):
        print(i)
        eventsForFiltersGUI.append(np.array([[]]))
    else:
        eventsForFiltersGUI.append(np.array(event[0]))

# filter centroids
filterCentroidsGUI = []
for mask in masks_gui:
    cX, cY = find_centroids_from_binary_mask(mask)
    filterCentroidsGUI.append([cX,cY])
filterCentroidsGUI = np.array(filterCentroidsGUI, dtype="uint16")

241
249
265
270
272
277
281
289
293
294
306
307
315
320
321
322
323
330
338
339


In [182]:
eventsForFiltersGUI[0]

array([ 565, 1002, 1663, 3223, 3283, 4735, 6104, 6216, 6224, 8315, 8640],
      dtype=uint16)

In [220]:
#we wanna look like this
pca_ica_w = scipy.io.loadmat("/home/user/Documents/single_session/dataPackedForGeneration.mat")
eventsForFilters = pca_ica_w["eventsForFilters"]
eventsInFrames = pca_ica_w["eventsInFrames"]
filterCentroids = pca_ica_w["filterCentroids"]
filtersBinary = pca_ica_w['filtersBinary']

# #load gui mat
# gui_mat = scipy.io.loadmat('/home/user/Documents/single_session/GUI/synthetic/gui_extracted_wo_added.mat')
# #gui_mat = scipy.io.loadmat('/home/user/Documents/single_session/GUI/singleshot/gui_extracted.mat')
# coords_gui = gui_mat["coordinates"][0]
# events = gui_mat['events'][0]
# traces = gui_mat['traces']
# #load movie belonging to gui data
# movie_path = '/home/user/Documents/synthetic_datasets/sequence_9/video/movie.h5'
# #movie_path = '/home/user/Documents/single_session/preprocessed/preprocessedMovie.h5'
# movie = load_preprocessed_movie(movie_path)


# Opening JSON file
f = open('/home/user/Documents/synthetic_datasets/sequence_9/data.json',)
  
# returns JSON object as 
# a dictionary
data = json.load(f)
coords_gui = data['neuron_coordinates']
events = data['neuron_events']
traces = data['neuron_activities']
# Closing file
f.close()




# events_cnmfe_added = spike_finder(traces[340:len(traces)])
# events_cnmfe= np.array([np.array(x) for x in events_cnmfe_added])

    

# events_new = []
# for event in events[0:340]:
#     events_new.append(event)
# for event in events_cnmfe:
#     events_new.append([event])
# events_new = np.array(events_new)

events_new = events
# filters binary
masks_gui = []
for coord in coords_gui:
    mask = binary_mask_from_contour(coord)
    masks_gui.append(mask)

masks_gui = np.array(masks_gui)
filtersBinaryGUI = np.transpose(masks_gui, (1, 2, 0))



# eventsForFiltersGUI
eventsForFiltersGUI = []
for event in events_new:
    if not list(event):
        print("yes")
        eventsForFiltersGUI.append(np.array([[]]))
    else:
        eventsForFiltersGUI.append(np.array(event))

# filter centroids
filterCentroidsGUI = []
for mask in masks_gui:
    cX, cY = find_centroids_from_binary_mask(mask)
    filterCentroidsGUI.append([cX,cY])
filterCentroidsGUI = np.array(filterCentroidsGUI, dtype="uint16")


In [212]:
filterCentroidsGUI.shape

[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]


In [183]:
i = 0
size = 0
for event in events_new:
    size += np.array(event).size
    if np.array(event).size == 0:
        i += 1
print(i)
print(size)

20
88434


In [213]:

eventsInFramesGUI = []
for i in range(movie.shape[0]):
    frame = np.zeros((500,500))
    frame_events = []
    for j, (events_single) in enumerate( events_new):
        if not list(events_single):
            continue
        for event in events_single[0]:
            if event == i:
                frame_events.append(j)
                                              
    
    
    if not frame_events:
        #frame_events = np.expand_dims(np.array([],  dtype='float64'), axis=1)
        frame_events = np.array([],  dtype='float64')
    else:
        frame_events = np.array(frame_events, dtype='uint16')
        print(frame_events)
    eventsInFramesGUI.append(frame_events)
    

eventsInFramesGUI = np.array(eventsInFramesGUI, dtype='object')


[ 61  92 205 387 489 503 592]
[224 388 429 476]
[376 456 503 506 520 528 562]
[402 444 460 488 499]
[352 378 438 471 487 580 607]
[ 83 165 250 316 485 532 550 568]
[206 354 480 537 615]
[333 444 521 569 575 614]
[ 23 176 438 555]
[254 351 381 387 392 414 458 514 524 572]
[121 301 347 365 371 383 391 437 466 485 499 536 564 593]
[262 352 396 427 477 532]
[464 488 498 502 562 592]
[  6  79 189 411 429 460 480 518 555 598]
[136 461 552]
[ 31 352 464 488 565 576]
[ 63 100 195 237 238 319 425 438 479 552]
[ 46 481 562 572 581]
[346 532 543]
[ 84 110 383 405 417 531 552 572]
[189 396 425 478]
[258 342 351]
[ 55 383 392 396 425 508 581]
[487 532 614 615]
[ 43 198 237 344 436 456 488 521 531 565 566]
[ 22  32 497 504 536]
[ 16 210 251 258 351 352 409 537 551 552 562 593]
[100 238 319 377 481 507 572]
[  6 598 614]
[346 535 615]
[ 84  92 392 396 499 537 581 614]
[ 43 177 354 405 460 497 565 576]
[ 23  32 161 319 342 392 395 464 474 532 537 538 575]
[146 258 371 373 383 425 427 552 555]
[141 564

[371 428 457 493 521 560 603]
[376 377 429 455 503 525 546 551 581]
[ 61 275 373 381 392 414 458 460 486 497 568]
[225 351 368 457 461 499 566 597]
[ 53  85 408 472 523 532]
[ 30  92 126 368 402 537 557 580 584]
[198 373 553 555 590 598]
[127 313 571 576]
[ 57 258 491 501 540 573]
[ 38  70 472 557]
[478 493 496 523 528]
[113 180 301 358 364 370 440 602]
[ 61 378 381 392 414 437 521 575 582]
[  7  33  48  58 359 457 491]
[ 77 381 392 408 414 435 437 503 555]
[267 369 444 482 499 524 569 585 594]
[364 479 486 540 581]
[ 64 127 206 393 494 505 559 595]
[106 119 161 216 236 359 366 368 401 415 455 603]
[258 409 437 447 482 524 568 578]
[245 472 503 536 539]
[ 84  97 298 372 413 471 532 538 552 576]
[ 92 164 220 260 352 400 402 465 497 615]
[  6 354 378 407 521 608 614]
[254 371]
[  9  33  63 177 267 376 381 414 472 539 555]
[205 225 373 392 477 553 566 569]
[206 440 491 557]
[127 305 415 528 575]
[106 358 385 493 501 571 586]
[  7 147 159 408 436 476]
[ 61 136 258 387 437 474 584]
[ 27 374

[314 396 475 562]
[393 406 450 500 505 508 532 590 611]
[ 72 228 258 366 367 425 428 447 521 543 553 559 577 595]
[427 438 443 541 564]
[507]
[ 64 377 393 408 411 447 479 481 494 521 579]
[ 49 109 194 303 347 397 500 543]
[363 407 480 499 503 514 555]
[374 482 611]
[186 396 401 438 440 506 509 521 532 553 574]
[359 400 447 475]
[119 206 279 357 366 406 411 430 443 481 494 543 566]
[ 28  39 369 393 427 500 507 593]
[179 196 208 251 359 374 384 397 411 442]
[ 14  61 311 420 455 499 503 526 536 573]
[235 363 396 402 508 514]
[106 198 347 369 371 456 457 482 511 515]
[105 161 379 400 411 494]
[ 35 185 217 447 468 521]
[ 57 377 403 481 615]
[ 64 107 136 224 314 502 578]
[109 134 164 177 235 369 383 398 499 506 564]
[ 61 372 415 420 503 510 538 566]
[ 45  70 206 407 456 473 504 537 568]
[119 251 259 359 396 442 461 532 574 580 592 604]
[220 317 383 408 480 513 514]
[ 41  54  92 198 258 434 438 491 588]
[346 378 471 499]
[286 351 352 438 478 481 497 547 615]
[109 193 207 316 354 378 469 565 5

[ 43  56  94 332 354 474 477 614 615]
[ 92 301 381 392 414]
[212 382 400 406 413 425 485 504 513 537 594]
[193 225 344 371 372 385 399 447 517 604]
[ 27 147 382 396 431 479 586 600]
[ 84 132 245 302 342 369 373 415 514 530]
[397 431 468 471 546 580 603]
[ 38 383]
[305 388 454 461 474 476 532 533 538 540 590]
[ 54 135 150 225 316 384 566 574]
[146 378 500 544 553 575]
[480]
[ 97 407 438 442 465 478 526 548 549 572 587 615]
[468 481 487 499 564]
[167 280 482 551 613 614 615]
[ 11  18 131 354 377 460]
[ 81 258 493 565 581 613]
[ 43  69 377 547]
[165 254 311 378 381 392 414 468 593 601 615]
[233 301 376 429 540 586 614]
[ 55  64 214 237 387]
[177 256 373 374 382 396 462 491 495 511 533 537 578 580]
[145 454 458 485 504 527]
[225 231 403 413 592]
[ 41  54 193 376 383 384 406 426 457 461 486 514 573]
[391 397 424 549 584]
[ 85 317 379 454 463 560]
[ 86 247 275 362 364 377 407]
[299 392 498 600]
[ 27 374 385 419 431 472 501 543 578 603]
[160 216 220 337 358 399 452 473 478 491 507 508 528]
[ 

[ 75 125 205 364 428 457 472]
[ 85 145 371 377 495 536 539 564]
[143 147 170 399 428 440 493 496 501 519 602]
[ 38  70 159 303 473 478 503 553]
[482 499 537]
[ 33 538 544]
[ 56 377 381 392 414 480]
[ 68 200 437 476]
[ 54 145 373 430 486 497 536]
[151 258 267 359 363 388 400 433 505 548 585]
[132 255 299 319 524 527 592 599]
[105 119 475 479 525 540]
[406 428 500 523 541 595]
[169 228 369 417 427 440 447 494 507 521]
[ 57 164 217 393 482 540 571 585]
[112 125 438 443 468 499]
[ 49 149 240 377 425 440 447 508 562 580]
[368 397 402 539 541 581 604]
[ 39  64 208 303 506]
[ 28  56  99 109 313 314 326 420 468 503 521 564]
[258 357 372 455 538 568]
[ 54  97 251 298 347 373 407 413 437 480 491 566]
[376 457 510 588 608]
[ 41 407 437 444 455 461 471 506 532 541]
[ 40 190 206 317 440 466]
[149 258 373 396 400 456 500 514]
[382 385 406 415 477 495 511]
[ 54 299 328 468 474 485 493 497 530 547 548 574]
[ 79 373 378 403 471 480 537]
[395 466 473 481]
[ 43  59 207 216 316 482 517 566]
[111 114 354 3

[ 30 148 311 367 420 442 499]
[ 56  61 357 376 390 415 431 440 503 566]
[ 45  99 305 391 407 455 564 580 588]
[ 97 205 302 303 497 538 575]
[167 258 347 372 399 436 461 480 517 578]
[ 31 264 346 383 407 442 513 514 587 608]
[378 390 478 497 568]
[354 480 565]
[150 378 586]
[469 551 552 566 615]
[ 23  43 177 210 354 367 407 438 548 578 614]
[  4  11  56 207 436 485 516 547 568 615]
[ 98 447 460 495]
[149 198 258 385 401 506 517 590 614]
[ 50 342 373 388 392 425 462 500 586]
[ 41  54 145 305 347 371 461 575 614]
[146 353 357 372 455 471 511 593]
[ 14 109 385 417 425 541]
[ 27 206 374 389 395 409 475 495]
[ 17  28 318 400 514]
[216 369 373 508 513 517 547]
[383 429 532 537 566 588]
[ 54 207 316 352 480]
[ 16  35 475 500 502 601]
[  7  28  39  43 119 133 145 148 283 402 406 503 507 516 534 541 557 588]
[ 14  49  68 105 126 129 137 352 369 418 433 459 463 525 600]
[  8  87 111 161 359 363 428 455 456 533]
[179 208 592]
[ 92 149 158 167 314 384 456 461 514 531 533 575 604]
[ 17 110 209 340 3

[ 27 147 186 225 369 385 428 479 500 505 509 575 595]
[401 415 463]
[153 221 251 258 305 373 379 392 420 424 434 461 474 478 513 547]
[ 57  70 143 364 368 370 408 423 429 532 540]
[ 25 106 232 238 371 383 384 430 488 490]
[387 389 407 464 536 538 586]
[ 54 190 471 497]
[ 92 207 316 354 373 378 440 450 508 573]
[158 370 382 391 491 520 586 588]
[167 308 358 365 371 385 399 476 478 543 557]
[297 419 428 452 482 501]
[121 134 147 303 493 494 497 602]
[ 61 127 200 236 368 381 392 395 444]
[374 400 447 458 475 485]
[ 56 116 225 353 420 454 455 530 532 548]
[235 347 372 413 503 538 541]
[ 54 153 335 384 402 438 511 530 562 590]
[ 85 143 166 397 403 406 445 450 513]
[456 479 537 559 561 564]
[ 25  32 251 442 468 509 569]
[190 314 379 383 474]
[369 371 403 473 495 506 514 546 547 558]
[318 356 500 507 509 518]
[149 151 486 541 564]
[216 387 415 437 457 494 597 599]
[258 288 373 467 566 579]
[ 27  32  92 397 471 545 581]
[251 371 416 424 428 450 452 463 472 540]
[ 88 158 238 300 354 408 586]
[ 

[135 153 316 375 387 445 537 548]
[374 376 400 402 429 475]
[ 17 382 473 500 576]
[ 61 353 354 385 478 551 574 581]
[ 97 177 357 378 390 466 468 480 499 508 559 614 615]
[  6 280 460]
[ 21  77  81  98 354 438 485 549 568]
[203 352 392]
[145 402 500 538]
[ 28 109 149 198 206 318 351 383 385 396 415 485 493 514 571]
[147 222 347 450 461 479 509 513 524 560]
[137 251 358 396 397 406 440 445 475 505 536]
[ 54 400 413 415 504 514 538 592]
[153 185 384 397 423 424 434 456 462 471 472 513 569]
[ 85 447 464 477 548 558 578]
[280 468 541]
[168 478 500 578 594 604]
[ 17  28 203 340 475]
[145 149 209 508 574 575]
[258 359 415 457 486 577]
[238 251 260 426 595 597]
[ 30  85 319 364 424 434 435 471 551]
[313 384 469 478 546 570]
[373 388 408 472 581]
[ 54 354 465 481 499 539 551 562 563 569 614 615]
[ 98 108 164 438 482 515 565 572]
[ 41  81 118 259 352 552 568]
[188 390 480 493 497]
[  9 354 392 532 549 578]
[200 203 236 245 333 414 440 468 614 615]
[ 43 127 368 503]
[ 30 173 359 371 614]
[373 381

[240 365 374 416 417 571]
[209 373 422 428 504 514 584 615]
[ 17 402 438 503 580 592]
[342 371 379 383 461 516]
[208 258 351 513]
[174 295 352 378 382 407 436 473 547 548]
[260 375 390 392 442 551 604]
[ 77 178 404 565 581]
[346 354 378 522 579 614 615]
[137 319 465 481 568 572]
[ 43  81 108 116 390 587 614]
[429 493]
[173 480 551 586 614 615]
[391 446 470 485 543]
[365 434 499 541 545 558 581 589]
[203 353 584]
[290 392 414 417 540 565 614]
[440 522 580]
[462 502 552 553 590 599 615]
[154 296 340 351 353 401 511 566 614]
[228 367 413 425 468 518 565 569 584]
[ 34  55 210 342 416 478]
[423 425 513 545 586]
[362]
[ 57 147 359 442 508]
[136 258 402 416 469 481 548]
[175 363 368 389 434 438 465 473 482]
[ 28  56 378 390 447 480 492 493]
[203 236 354 368 405 532 537 614 615]
[  6  81 127 352 569 579]
[108 116 258 438 468 495]
[480 538 615]
[ 68 354 414 446 457 485 614]
[260 317 366 379 385 458 471]
[290 371 413 492 493 505 518]
[ 16 352 436 469 585]
[ 43 390 431 456 497 522 615]
[422 440 6

[ 68 108 178 301 346 352 375 522 565 581]
[ 32  52  88 203 551]
[388 414 485 495 540 547]
[390 395 538]
[ 98 258 373 378 383 392 413 414 545]
[171 381 382 387 425 430 461 503]
[145 356 401 423 482]
[161 359 402 412 468 586]
[136 162 353 513 601]
[137 233 532 580]
[207 378 404 442]
[ 55 354 497 558]
[316]
[ 56 351 382 444 518 568 602]
[145 171 413 438 590]
[356 387 423 449 461 470 498 502 537 571]
[132 136 406 445 514 584]
[ 32 508 562]
[267 366 371 378 477 493 565 576]
[121 465 540]
[254 390 404 478 481]
[ 81 354 363 615]
[110 442 614]
[438 485]
[ 43 171 212 342 381 392 397 414 425 460 518 584]
[ 61 237 258 373 383 424 440]
[145 162 220 301 384 504 511 518]
[383 402 458 548]
[182 397 425 449 474 475 500 505 507 509]
[147 347 479 569 571 599]
[135 153 374 385 396 415 422 514]
[209 335 402 406 486 505 540 541]
[216 384 425 426 475 560 579 581 590 593]
[ 59 400 427 481 500 509 521 564]
[ 50  57 203 366 406 443 499 507 579 593]
[ 14 164 179 258 303 367 368 384 393 444 494 553]
[ 64 101 250

[ 28  46  83 438 468 498 614 615]
[ 81 258 346 354 572]
[ 52  98 392 395 497 499]
[203 374 396 461 485 504 589]
[245 301 342 425 431 555]
[ 92 153 158 197 209 290 371 383 416 540]
[258 428 452 493 560]
[162 173 286 408 450 504 540 586]
[ 58 211 224 358 434 472 476 491 520 591 595]
[ 38 159 168 280 377 404 602]
[ 61  69 182 303 349]
[ 28  77 116 258 267 381 388 392 414 416 420 503 537 547]
[387 558 563]
[353 376 396 423 485 498 547 574]
[434 502 506 514]
[475 513]
[ 46 256 371 374 461 470 504 548 586]
[301 488 538 549 578]
[135 197 354 375 382 413 444 513 559]
[ 70 380 404 565]
[  6 378 442 509 551 581]
[167 173 203 354 477 480 563 588]
[ 33  98 369 378 481 548 565 587]
[188 284 390 394 442 450 517 541 615]
[295 346 352 381 392 414 581 614]
[  9 313 378 456 480 522 544 549]
[ 43 158 245 404 525 615]
[232 354 504 568]
[401 438 574]
[166 197 344 375 395 416 457 485 540 586]
[178 404 434 493 545]
[243 416 449 584]
[147 374 385 387 389 422 423 431 518]
[216 443 507 509]
[136 173 359 383 504

[237 399 407 491 497 498 501 508 532 604]
[156 222 404 468 478 480 502 564 567 595 611]
[ 23 258 358 419 493]
[136 212 354 404 478 497]
[106 114 203 234 378 381 414 460]
[172 368 392 395 396 423 437 449 485 511 518 540 589 611]
[105 216 245 342 390 452 574]
[ 19 134 153 240 347 357 366 413 415 423 425 474 586]
[ 57  73  77 258 383 387 388 406 420 434 498 538]
[324 374 375 440 467 478 480 488 513 551]
[237 371 372 378 477 491 503 586]
[404]
[ 61 378 383 390 429 458 565 567]
[407 446 581]
[  4  98 268 354 480 481 497 521]
[ 23 316 375 381 547 615]
[ 52 173 203 344 376 404 438]
[264 267 351 355 374 392 396 414 416 417]
[ 18 369 373 381 387 413 423 440 474 513 514 586]
[185 230 406 431 461]
[132 193 258 356 387 389 439 459 503 561]
[169 335 462 516 589 600]
[365 372 416 417 588]
[197 257 403 470 493]
[318 349 382 413 444 445 491 506 527 541 569]
[ 19  77 208 228 390 466 477 611]
[ 57 131 384 407 426 454 540]
[292 301 376 394 480 548 566 567 573 614 615]
[404 559]
[353 369 379 387 480]
[182

[457 480 528 548]
[378 385 438 465 551 568]
[ 81 110 390 404 450 478]
[ 83 118 188 346 354]
[ 52 351 381 392 414 490]
[ 18 116 171 209 518 533]
[247 251 260 286 371 383 424 435 436 463 472]
[ 30  53 106 145 205 493 494 503 562 586 594 595]
[ 38  58  81 271 410 455]
[162 351 370 404 407 416 417 446 458]
[373 441 454 491 503]
[170 198 220 391 401 449]
[213 353 406 423]
[ 63 357 364 401 422 437 444]
[167 373 417]
[480 518]
[ 79 258 378 487 513]
[203 346 354 490 568 610]
[ 77 468 476 614 615]
[ 52 316 498 532 543 548]
[267 340 373 375 376 381 392 414 417 477]
[154 205 365 387 395 449 589]
[121 173 377 385 391 416 440 478 491 501 506 511 570]
[147 170 399 428 431 493 496 499 564]
[417 539]
[364 370 385]
[ 38 203 369 419 600]
[106 160 172 216 404 521]
[222 468 492 522 551 568 587 610]
[118 196 354 457 480 592]
[267 319 340 381 392 414 477 485 500 521 540 590 610]
[209 225 301 396 406 437 471 486 527 548 569 585]
[135 153 258 342 364 447 449 475 505 521 562 581 599]
[ 50 105 261 302 425 500 5

[220 317 364 394 413 454 467 528 546]
[282 356 567 573]
[137 203 357 403 471 504]
[ 83 472 473 596]
[149 158 400 434 461 463 545]
[173 413 441 444 447 450 462 592]
[258 297 369 370 380 490 493 543]
[260 340 424 538]
[192 202 300 403 457 467 470 506 546 558 559 570 577 603]
[226 434]
[465 486 492 545 547]
[ 58 167 195 354 378 390 468 471 480 551 572]
[438 442 447 529 566]
[ 83 477 485 568 581 614 615]
[ 98 378 404 465 480 481 535 544 551]
[390 399 468]
[354 485 497 543 579 614]
[203 431 435 457 480 490 615]
[114 346 560 581]
[ 46  80 386 580 604 614 615]
[258 438 529]
[113 213 388 469 567 614]
[352 404 465 485 551 615]
[313 390 480 481]
[ 46 184 485 514 521 580 614 615]
[137]
[  4 210 438 442 549 552]
[237 565 569 572]
[ 81  83 108 168 203 406 466 468 610]
[434 485]
[158 417 543 545 614]
[240 371 379 381 392 414 423 457 493 575 599]
[372 387 449]
[193 254 260 368 391 413 461]
[380 384 408 423 540]
[141 172 317 373 439 455 571]
[374 514]
[206 356 364 394 419 455 500 569 573]
[ 79 137 147

[125 153 404 406 482 511]
[ 38 431 438 445 458 471 477 528 551 574 576]
[ 46 354 378 490 496 588]
[216 480 551]
[ 33 404 414 469 529 558]
[ 52 344 381 392 412 468 480 569]
[ 59 354 362 378 390 406 417]
[203 438 552 592 600]
[ 55 195 233 267 316 347 381 392 414 461 474]
[ 72 382 413 416 440 468 547]
[ 61 121 181 375 493 541 570 595]
[193 394 399 417 431 445 513]
[390 466 529 538]
[ 77 346 354 378 465 468 485 568 615]
[ 52 184 438 480 614]
[324 347 381 392 396 401 414 449 474 509 569]
[149 340 353 371 500]
[136 158 216 501 514 538 580]
[ 54 153 356 380 383 416 423 457]
[304 347 349 373 374 434 449 450]
[192 356 371 379 413 472 474 513 524 537 541]
[132 185 388 389 403 434 436 441 461 463 505 528 545 559]
[233 260 364 424 471 504 571]
[ 72 462 486 567]
[ 48  93 167 383 429]
[ 85 417 488]
[402 449 505]
[353 357 404 442 455 503 568 576 591]
[197 275 457 518 538]
[158 288 356 378 522]
[ 41 132 192 245 424 449 463 504 592]
[ 88  94 136 256 358 435 452 472 493 540 603]
[ 43  53  85 271 279 364

[128 240 478 503 564 574]
[ 45 340 415 538 558]
[ 15 182 258 377 378 413 455]
[ 41 207 347 353 383 389 405 407 437 529 558 559 571]
[ 72 192 415 526 543]
[316 404 478 518 575]
[369 394 415 431 453 547]
[ 21  70 358 374 385 399 434 436 508]
[314 369 490 558]
[ 77 367 390 404 551]
[ 11  32  52 415 477 538 572]
[ 28 237 267 313 381 392 414 437 453 586]
[245 251 367 529 543 587]
[ 23 358 391 428 431 473 524 528]
[ 33 160 222 351 370 375 394 399 432 478 546]
[173 216 377 417 473 507]
[ 21 258 501 542]
[119 136 238 358 364 384 395 399 428 462 478 564]
[ 37 147 159 180 199 204 212 404 494 587]
[106 347]
[ 52  77 354 378 396 490 549]
[267 370 381 392 397 414 533 536]
[374 382 425 429 437 439 573 574]
[ 63 165 394 442 462 543 568 585]
[369 374 376 395 441 445 455 584]
[ 32 153 262 377 388 431 439 478]
[147 238 384 493]
[ 37 113 216 373 425 451 558]
[ 18  31 181 340 342 397 449 452 576]
[406 577 588]
[ 52 372 404 429 480 546 581 599]
[ 77 207 316 381 392 414 475]
[171 505 514 585]
[258 342 347 3

[346 390 405 418 468 481 497 502 529 555]
[ 77 189 210 238 308 384 460 478 488 552]
[ 26  45 353 434 441]
[288 416 588]
[ 98 404 438 480 526 535 558]
[113 258 301 383 437 481 552 572 592]
[  3 108 212 219 238 308 425 466]
[171 181 280 295 369 470]
[192 348 418 458 462 476 507 537 550]
[497 580]
[ 26  80 401 404 453 571]
[ 23 342 368 369 440 455 493 511 537]
[144 379 406 413 474 567]
[127 193 213 236 258 382 417 423 553 568 591]
[304 521 547]
[ 84 153 208 308 369 374 387 389 403 456 533]
[413 473]
[340 378 445 457 522]
[171 317 388 406 408 517 566]
[ 79 147 175 187 238 276 319 380 399 524 536]
[251 508]
[382 468 477 488 528 541 568]
[ 52 354 381 414 500]
[ 68 191 210 350 365 404 434 438 553 555 599]
[ 45 317 418 506 522 566 584]
[ 32 141 346 440 485 552 553]
[ 34 110 251 404 493 565]
[ 81 373 378 416 567]
[267 352 381 392 414 460 529 538]
[ 55 342 348 350 353 369 403 420 425 530 561]
[144 351 362 371 443 461 527]
[193 225 231 233 317 548]
[182 374 390]
[284 405 488]
[ 88 136 384 468 552

[137 207 344 368 409 470 480 574]
[378 588]
[ 18 376 417 485 551 568 581]
[316 352 390 446 468]
[ 59  94 301 354 381 414 490]
[ 52 264 473 614 615]
[158 392 553 569]
[ 18  46 232 240 390 444 560]
[197 369 382 413 435 462 482 545 600]
[ 61  92 342 403 423 548 567 584 589]
[ 57 193 383 391 394 431 434 504 536]
[143 309 387 417 425 513 586]
[147 153 258 340 356 374 461 524]
[335 394 403 413 423 440 472 474 493 537 540 541 573]
[ 72 364 382 389 416 441 468 595]
[401 429 454 519 537 592]
[340 389 424 463 471 500 504]
[ 40 380]
[ 85 217 275 394 406 436 522 575]
[169 230 379 384 424 434 444 501 531 557 595]
[388 540 547 570 600]
[344 391 399 428]
[389 416 466 493 567]
[131 190 192 284 384 387 461 463 474]
[ 25  75 238 243 251 257 349 416 443 597]
[354 374 417 424 472 478 486 496 539]
[ 70 112 147 160 333 399]
[359 364 369 559]
[ 83 209 444 473 540 569]
[ 40 191 245 359 365 381 392 401 414 551 552]
[ 18 163 267 349 377 413 457 476 536]
[ 72 387 436 455 496]
[135 371 379 385 388 401 440 482]
[1

[236 392 455]
[ 21 147 180 303 364 370 385 399 428 493 501 564 565]
[ 81 106 419 431]
[378 381 414 420]
[344 392 438 536]
[207 347 353 381 485]
[362 387 390 413 434 458 474 521 522 526 529 536 545 599]
[ 56 279 352 369 401 405 423 457 484 559 569]
[ 81 192 350 429 456 552 584]
[258 317 347 379 406 412 433 547]
[179 198 340 387 403 449 450 463 466 503 519]
[131 193 373 423 452 461]
[153 185 365 394 471 513 516 537 538 592]
[ 72 383 400 413 434 435 441 448]
[141 389 406 424 504]
[364 454 463 518]
[ 85  86 486 519 543 597]
[ 51 132 224 230 238 356 362 384 391 394 426 464 466 484 494 516 533 573
 579 598]
[308 376 385 421 428 441 478 526 528]
[131 364 491 516 573]
[127 217 368 417 430 507 527 575]
[ 95 200 257 365 379 434 435 446 456 549]
[340 370 424 429 471 559]
[ 54 297 409 455 473 490 551 597]
[ 97 202 219 545 591]
[ 75 354 378 383 390 417 480 533 568]
[258 392 529 536 573]
[ 18 429 487 502]
[182 428 463 533]
[238 308 419 448 494 520]
[385 410 457 478 533 577 595 600]
[106 147 399 404 

[258 275 365 387 388 394 413 573]
[357 380 434 441 529 540]
[185 364 400 447]
[379 426 454 462 491 504 521 547 574]
[ 57 150 445 449 456 486 541 548]
[ 79 383 397 429 521 527 581]
[ 54  75  83 258 402 415 419 463 507 513 529 545 573]
[238 257 261 380 384 434 435 448 577]
[410 424 478 571 599]
[165 192 237 371 450 486 594]
[457 574]
[ 73 385 408 433 447 524]
[167 219 250 364 399 416 443 475]
[222 308 428 431 472 493 507 603]
[ 57 258 370 396 521 591]
[402 427 437 445 463 527 569 594]
[371 457 502 503 504 518 525]
[ 41 150 415 452 462 475 505]
[170 225 366 371 408 509 540 585 595]
[192 404 503]
[ 56  61 238 458]
[354 368 434 461 467 478 503 552]
[ 35 257 258 347 357 383 416 460 529]
[ 88 113 344 348 372 376 387 423 438 454 513 548]
[127 225 383 413 445 456 461 511 541]
[193 403 488 567]
[ 54 149 413 464 513 551]
[ 61 335 390 481 488]
[460 465 480 551]
[ 94 164 313 490 500]
[188 350 354 378 544 577 581 615]
[192 346 477 485 492 614]
[127 219 254 352 368 390 404 408]
[ 52 378]
[ 46  56 168

[ 52 171 422 603]
[267 367 381 392 414 500]
[148 347 370 402 493 540]
[385 452 471]
[ 70 114 167 370 371 419 491 493 509 527]
[113 358 428 437 441 518]
[ 58 366 371 560]
[ 61 182 381 392 396 398 414 416 471 504 546 584]
[170 225 261 449 457 475 505 509]
[153]
[ 32  93 134 169 209 420 464 467 494 503 515 552]
[365 435 519 536 597]
[ 54 290 347 382 390 403 413 454 491 511 513 525]
[344 463 486]
[ 30  86 162 362 391 447 470 506 520 575]
[ 25 168 384 410 462 471 477 532]
[188 350 429 548]
[ 59  70 311 354 378 468 480 533 568 583]
[490 566 581]
[203 209 350 492 551]
[264 280 354 390 417 480]
[ 52 504]
[197 353 387 486 495 536]
[ 86 358 371 424 428 452 501 505 516 570 593 599]
[ 58  85 160 162 251 410 460 463 496 543]
[125 170 401 416 475 540 600]
[ 35 185 406 444 507 593]
[209 216 302 505 509 541 581 589]
[105 261 412 521 593]
[ 75 169 355 401 425 427 443 475 481 495 500 507 516 541 579]
[ 14  64 119 134 164 367 393 402 494]
[106 125 470]
[314 347 362 372 417 420 458 482 503 511 515 538]
[ 

[460 552]
[344 392 508 545]
[267 316 376 381 403 414 420 513 584]
[ 61 207 348 369 387 423 464]
[121 193 324 344 353 388 406 438 461 470 506 539 547 574]
[402 445 522]
[350 371 535 551 570]
[131 378 492 541 553 565 566]
[118 245 290 350 390 465 468 480 581 588]
[354 526 614 615]
[171 381 392 414]
[  6 384 471 485 554 567]
[280 481 523 572]
[219 316 438 614 615]
[475 481]
[ 74 222 368 391 417 459 514 516 572 589]
[ 18 129 163 167 177 194 251 258 304 348 382 397 434 440 443 476 507 527
 533 541 571]
[ 76 193 365 446 457 503]
[ 57 112 121 174 352 406 470 491 507 564]
[ 66 340 424 473 515]
[ 79 202 466]
[ 74 258 371 394 403 531]
[ 46 260 364 383 387 397 410 413 423 470 513]
[101 153 347 403 406 506]
[379 402 485 592]
[173 185 340 380 408 538]
[ 75 169 413 508 518]
[ 25 219 384 394 424 461 504 573]
[206 362 368 463 471 516 539]
[161 203 402 432 464 574]
[127 340 368 415 419 422 447]
[383 385 397 410 437 457 471 477 486 501 567]
[258 288 364 384 415 493]
[167 385 391 399 422 428 543]
[ 21 21

[77]
[406 426 439 463 484 533 575]
[153 219 364 387 401 413 434 436 454 496 519 537]
[ 54 403 450 471 472 486 528]
[190 296 461 537 547]
[ 75 200 210 275 312 359 364 370 484 545 597]
[ 25 195 236 261 308 349 424 440 452 496]
[ 70 152 160 167 214 399 472 476 501 581 586 595]
[134 370 416 423 435]
[374 444 504 544]
[168 247 357 388 389 401 484 490 559 573 593]
[ 40 371 384 415 450 496 543 564]
[155 215 312 316 364 374 424 442 531]
[136 160 162 258 269 303 308 501 520 545]
[ 58  70 238 271 358 373 399 428 443 478 494 496 542]
[ 69  81 119 212 250 407 545]
[ 77 106 280 398 462 498]
[347 381 392 414 434 444]
[243 258 260 267 380 387 396 419 449 454 536 575 592]
[ 25  63  72 143 401 423 541]
[125 153 347 406 413 450 464 504 513 538 540 557 571]
[ 54 185 379 426 435 463 528 544]
[190 415 424 434 471 472]
[ 61  75 168 169 181 247 354 403 404 450 464 504 583]
[208 353 384 394 537 543 559]
[ 18  57 417 419 426 446 507 518 527 541 575 584 597]
[ 40 251 276 365 384 454 457 463 471 504 509]
[ 70 11

[316 346 417 422 429 494 576 581]
[353 354 378 445 456 490 518 614 615]
[ 74 350 473 480 496]
[ 59 477 478 607]
[ 84 171 375 417 460 476 546]
[383 425 439 453 474 556]
[ 86 170 200 225 236 370 385 391 501 524 527 536]
[127 257 365 368 417 421 440 446 464 507]
[370 385 416 457 478 543 600]
[ 21 160 258 308 363 399 419 428 473 494 501 508 564]
[ 62  64  81 147 172 358 390 477 496 531 542 611]
[ 61 137 348 460 567]
[ 77 385 462 598]
[ 33 175 254 354 378 392 493 574]
[121 358 381 414 570]
[ 56 119 267 303 368 379 398]
[127 396 406 412 460 538 588 606]
[ 63 239 413 423 434 449 450 471 513 521]
[153 309 396 403 452 464]
[ 54 257 347 434 495 541]
[384 397 424 513 533 591 592]
[316 344 378 383 437 450 457 458 471]
[518 529 597]
[ 74 380 479 520 544 567]
[261 362 397 415 513 593]
[ 32 119 185 350 371 457 463 486]
[364 438 478 509 528 543 577 592]
[155 167 383 416 422 464 465 474]
[237 326 369 421 477 490]
[ 62  84 353 434 464 471 546]
[372 551]
[ 43 257 316 384 435 472 473 533 536 547 588 597]


[ 63 206 347 376 435 461 464]
[131 185 384 454 463 471 505 516 570 571]
[ 86 248 288 340 434 534 541 589]
[ 76 161 365 402 417 446 464 527 539 581]
[ 18  29  79 182 442 543 568 576]
[ 61  77 174 352 400 480 551]
[ 74 354 429 494 544 614 615]
[ 46 378 426]
[ 52  83 346 350 380 390 422 490 525]
[ 84 392 419 449 453 457]
[192 205 209 243 275 428 461 464]
[ 92 170 371 385 399 472 486 570]
[477 478 493 501]
[370 381 392 414 447 567]
[406 416 437 485 500 509]
[ 17 192 216 475]
[242 283 346 404 480 487 551]
[254 354 376 390 465 481 492 526 581 598]
[ 46  52 174 280 392 414 425 446 485]
[374 381 396 402 475 500 541 569]
[342 400]
[ 28 148 186 209 402 427 486 505 509 514 571 577 593]
[ 74 261 397 415 439 517 574]
[420 504 508 513]
[347 461 467 538]
[  6  54  55 344 383 434 497 529 547]
[354 378 407 522]
[ 26 350 384 535 551 552 574 581]
[346 351 468 490 614]
[ 52  98 390 465 568 615]
[118 378 438 490 533 545]
[209 344 348 398 583]
[ 55 113 173 454 464 474 580]
[384 496 536 537 551 586]
[417 502

[ 28  50  64 134 190 385 507 521]
[ 56 172 261 503 536 564 597]
[101 232 429 457 463 506 532 538 586]
[ 45 347 362 363 419 420 433 434 455 478 495 519 530 552]
[334 399 431 437 454 467 476 496 513 573 575]
[ 79 131 223 340 355 369 394 536 547]
[ 20 155 379 391 476 478 510 529]
[ 70 362 407 463 477 483 496 547]
[ 54  95 235 417 448 516]
[ 66 431 477 491 493 520 570]
[143 358 364 385 395 399 421 428 436 478 528 543]
[333 363 382 419]
[ 37 355 370 376 573 574]
[381 583]
[ 56 390 490 562]
[ 33 369 381 392 414 420 439 477 536 538]
[243 290 394 413 449 458 471 490]
[139 259 434 454 464 552 577]
[ 18  63 316 346 516 591]
[347 362 387 403 454 537 539 607]
[423 452 464 471 513 557 595]
[190 379 403 408 454 463 596]
[ 54  72 260 362 364 424 436 518]
[ 85 366 457 472 486 503 520 528 595 597 600]
[ 86 354 382 462 477 539 584]
[419 421 437 453 493 501 524 528 570]
[399 428 494]
[ 37  62 147 159 212 358 363 477 478]
[113 167 222 370 437 586]
[ 33 160 311 378 449 490 544]
[ 56  77 106 275 577 596]
[3

[171 258 283 347 367 407 415 453 585]
[ 21  33  62 385 425 431 436 478 556 567]
[130 337 353 358 428 542 543]
[119 124 147 350 391 399 419 538]
[236 269 482 520 533]
[ 37  69 194 197 344 370 404 516 557 558 570]
[ 56 121 159 178 375 376 398 412 439 460 463]
[ 31 209 261 342 366 396 406 417 424 479 558 585]
[216 387 451 521]
[ 29 302 379 415 434 460 475 488 500 503 514]
[ 63 153 243 347 423 454 464 480]
[ 15 198 206 344 369 381 387 394 403 407 434 438 461 474 547]
[178 445 513 558 559 574]
[113 268 351 406 407 433 480 490]
[ 29 340 382 383 548 552]
[192 279 312 352 369 413 513 547 567 583]
[172 251 316 354 477 541]
[178 193 264 301 348 375 403 407 429 519 539 586 591]
[ 46  79 387 413 417 474]
[153 340 348 356 407 431 434 513]
[ 63 185 312 394 516]
[139 233 376 406 434 524]
[179 257 364 369 383 428 453 526 556 573]
[376 391 394 399 422 435 439 501 516]
[ 32  65 337 365]
[370 395 415 421 453 524 528 543]
[119 124 422 428 494 496 508 600]
[189 269 385 399 435 501 520 607]
[ 37 358 363 419

[ 74 210 366 427 447 468 526 533 573]
[420 434 576]
[ 40 362 411]
[ 49 349 357 377 378 390 468 502 562 572 576 593]
[ 77 410 420 509 543 550 552]
[ 78 225 250 372 403 437 462 544]
[ 70  73 162 349 457 458 496 581]
[ 56 221 260 546 548]
[353 354 406]
[371 475 479]
[ 93 280 401 416]
[174 216 427 509 516 521 565]
[191 351 404 419 457 494 517 523]
[ 90 125 296 456]
[  8  77 402 420 435]
[268 372 396 417 446 564]
[148 149 174 385 400 410 475 479 486 507 514 516 536 541]
[ 28  64  75  76  78 177 223 269 365 402 417 506 521 575]
[ 29 451 490 519 559]
[215 347 387 394 412 423 494 526]
[ 79 121 153 166 178 198 337 340 379 383 403 406 430 431 433 451 464 473
 491 506 513 547]
[ 56 453 459]
[ 40 251 458 467 504 506 536]
[ 88 257 407 429 435 461 470 471 508]
[477 492]
[219 354 378 385 480 556 569 576 583]
[118 316 350 404 526]
[354 438]
[ 52 171 355 381 392 453 570]
[149 371 382 403 414 420 462 511]
[ 18  40 290 384 387 416 424 439 536]
[ 88 193 344 353 390 412 455 498 502 529]
[ 78 182 410 461 52

[110 404 420 436]
[ 40 407 504 536 613]
[250 453 495 511]
[ 41 268 536 540 581]
[344 366 435 455 544 550 551 588]
[195 433 480]
[219 350 403 527]
[150 153 225 401 410 412 424 429 437 452 457 463 536]
[  8  78 251 358 371 372 384 448 471 486 493]
[ 30  58  70  86 162 364 399 428 490 496]
[ 37 143 161 290 452 462 505 509 544 548]
[351 404 449 526 531 591]
[106 368 377 396 420 475 544]
[127 149 427 437 449 569 594]
[216 261 397 406 425 458 494 507 520]
[153 309 342 367 393 479 509 521 527]
[ 39 169 195 240 357 419 427 536 588 596]
[134 198 394 426 448 527 584 589]
[ 31  86  93 105 225 376 397 516 525]
[125 196 202 399 484 492 494 495 523 551]
[191 362 427 454 517 552 566]
[428 519 521 533 579]
[145 376 406 458 509 572 573]
[269 454 484 523]
[219 419 475 531 581]
[  8  36  77 210 280 349 455]
[347 358 363 420 430]
[ 78 149 225 337 340 396 423 447 502 519 562]
[279 383 406 445 464 479 498 521 526 569]
[399 439 482 525 530 556]
[ 85 403 433 435 436 467 476 477]
[166 178 206 226 251 387 394 4

[ 29 100 347 420 434 536]
[153 259 349 357 377 383]
[ 35 206 219 386 467 471 522 566]
[ 73 346 349 468 498 552]
[174 210 280 354 378 517]
[404 420]
[203 346 378 458 465 551 579]
[ 23 442 572 581]
[ 28 110 137 346 353 378 481 535 538 614]
[457 518 615]
[138 481 492 565 572]
[ 74  81 174 259 386 390 397 404 485 501 535 545]
[161 217 381 500 544 613]
[ 84 145 149 171 340 352 383 392 420 439 468 490 518 529 536]
[416]
[ 40 219 383 408 454 473 488 536]
[198 290 387 513 570 586]
[  1 351 435 471]
[110 238 344 354 378 404 419 460 526 532 568]
[ 43 232 350 407 468 504 535 549 614 615]
[192 439 533 560]
[ 41 209 353 416 420 424 446 462 476 504 536]
[145 371 375 403 412 435 436 455 461 485 513 545]
[205 206 221 268 290 347 348 369 406 462 491 501 503 506 516]
[387 388 409 413 430 446 449 470 505 527 561]
[ 18  76 121 365 369 391 394 433 464 476 485 541 545 547 559 591]
[ 29 193 240 428 445 451 479]
[153 340 406 433 468 488 513]
[ 46  79 185 197 335 348 383 403 413 416 423]
[ 49 103 260 344 351 4

[363 424 536]
[ 29 402 451 453 532 558 578]
[258 347 391 394 538 556 594]
[ 63 134 340 369 413 415 513]
[ 15 206 223 233 348 355 359 379 394 403 406 423 461 464 475 529 591]
[ 27 185 353 365 431 463 505 509 558]
[415 478 497 525 586]
[382 431 453 474 482 524 556 599]
[372 384 399 412 462 496 530 559]
[276 415 461 564]
[ 21 237 417 440 477 586]
[ 36 258 303 381 439]
[209 247 353 373 403 414 423 451 454 474 490 538]
[ 40  41  83 607]
[ 16 412 416]
[ 21 257 407 457 574]
[340 358 374 401 421 438 443 459 501 541 571 578]
[ 29  76 177 222 392 413 433 435 507 516 527 589]
[ 18  41 125 340 365 440 446 449 553]
[  2 163 268 296 406 457 460 473]
[ 27 388 413 437 450 451 480]
[ 11 101 232 368 372 374 403 431 461]
[ 53 153 340 464 505]
[350 366 453 544 574]
[257 356 461 464 555 556 573 591]
[ 21 147 303 347 352 376 380 382 394 407 423 438 445 453 463 524 576]
[134 302 335 371 429 441 444 451 472 581]
[ 49 202]
[424 434 505 513 531 568]
[ 54 233 258 435 516 599]
[ 13  85 243 284 441 449 463 464 486

[238 269 271 303 358 422 428 477 478 487 542]
[172 212 577]
[370 385 488 491]
[ 77 367 381 392 414 439]
[ 56 143 209 436 440 583]
[ 31 153 258 342 367 375 394 396 412 425 437 449 451 464 479 504 516 530
 550 575 585 587]
[261 366 406 475 521 544]
[ 75 279 363 367 468]
[379 458 467 477 538 544]
[ 29 369 407 415 461 501 601]
[258 383 468 560]
[  8  88 143 314 372 421 448 459 478 520]
[ 62  70 464 471 496 504 536 553 578]
[ 73 162 214 407 462 517 548]
[ 41 415 583]
[ 21 355 358 374 385 399 431 448 478 510 559 578]
[395 457 490 498 502 512 525 543 576]
[  8 225 314 375 417 465 551 604]
[ 28 350 377 388 404 457 522 525]
[163 211 232 370 378]
[267 368 381 392 414 420 439 453]
[383 543 556 586]
[ 21 143 237 303 358 365 399 431 478 501 528 578]
[147 373 419 473 488 588]
[ 37  73 301 370 376 429 437]
[353 412 460 472]
[ 31 153 264 376 409 440 451 573 574 580 584]
[ 56  72 394 413 461 549]
[ 21  41 131 176 197 388 459 468 498 534 566]
[ 27  40 335 340 374 409 491 513 541 544 547 548 553 567 568 

[ 35  75 185 261 372 403 437 454 462 475]
[166 178 206 351 387 406 464 470 538 562]
[ 54 354 404 467]
[ 29  40 145 247 372 407 430 433 434 592]
[162 423 445 471 477 485 538]
[340 356 373 390]
[198 376 433 464 513 516]
[394 417 462 573]
[103 409 412 436 439]
[ 46 196 352 365 400 461 513 538 591]
[153 413 524 537 560]
[257 356 382 421 439 453 513 556 573]
[ 37 132 258 445 451 505 526 530 559]
[325 372 374 453 461 507 509 528 550 556]
[340 524]
[312 388 403 406 463 522 570 571]
[124 147 178 340 399 431 478 501 524 528]
[358 364 365 477 538]
[ 32 276 374 564 578]
[ 40  41 236 238 247 251 388 391 415 421 428 429 476 482 496 531 543]
[ 21 119 208 237 269 358 399 439 478 494 501 528 542 556 560 602]
[202 395 473]
[ 37 329 358 367 370 374 453 578]
[477 516 559 572 599]
[ 13  72  85 132 225 351 356 359 385 394 436 437 453 519 536 543 575 579
 607]
[ 21  59 156 352 391 421 428 526 530]
[124 221 238 269 377 384 385 399 473 478 501 508 524 528 529 531 568 578
 600]
[ 62 147 154 159 303 358 367 521

[165 301 354 368 503 568]
[250 347 547]
[110 127 236 258 350 368 420 490 545]
[ 18 176 403 433 434 536 537 549 584 593]
[ 85  86 168 313 383 408 416 424 449 486 545 570]
[  5  30 160 201 371 398 412 579]
[ 54  94 458 460 473 492 527 584 586]
[283 603]
[170 304 371 496 591]
[106 358 424 472 475 479 482 493 501]
[ 58  70 364 373 478 496 524 528]
[213 428 452 457 540 546]
[159 162 197 419 493]
[127 182 368 370 381 392 396 398 412 414 437 444 577]
[ 31 449]
[367 393 427 437 475 479 486 500 541 551 593]
[169 261 521 548]
[ 75 302]
[ 36 164 177 235 372 415 420 460 467 503 552 566]
[ 29  45 354 401 434 522]
[168 298 447 497 553 588 599]
[430 549 551 584]
[ 55 335 350 366 433 480 483 522 552 553 563 581]
[206 465 492 555 584]
[346 378 458 478 497 502 522 577 579 599 614 615]
[231 280 429 498 553 581]
[317 470 492 497 531 541 544 551]
[ 81 118 402 522 558 565 578 585]
[110 186 354 487 572 581]
[ 43  52 243 304 409 430 583 584 615]
[398 465 552 614]
[ 23 168 378 386 401 555 564 569]
[ 45 189 468

[372 374 412 415]
[251 257 387 407 435 440 464 580]
[ 41 247 335 511]
[125 162 202 268 368 375 410]
[262 352 406 433 554]
[103 236 390 423 431 438 538]
[ 46 127 344 368 461 491 521]
[ 32 101 437 447 456 474 537 583]
[ 63 383 492 562]
[399 477 479 490 574]
[ 17  83  88 383 421 480 522 526 544 555 599]
[168 192 287 478]
[350 500 580]
[243 301 378]
[ 52 171 352 375 402 416 462 570]
[166 409 410 445 477]
[141 153 178 383 563]
[127 368 374 385 416 431 493 501 517 524 556]
[ 91 159 197 237 240 399 421 428 445 477 494 519 564 571]
[ 39 136 147 232 370 479 488 507]
[ 21 284 437 563]
[ 33 115 211 398 414 583]
[212 337 355 370 416 529 559 564]
[ 31  63 380 396 399 406 424 437 449 451 593]
[ 17 258 261 385 479 500 521 526]
[ 27 148 216 250 367 372 525 538 578]
[256 347 415 461 467 576]
[153 248 366 383 433 436 477 495 544 574]
[110 173 192 471 478 518]
[415 458 522 529 578 585]
[ 70 137 211 383 388 424 591]
[ 21 493 501 586]
[358 374 385 404 419 428 452 503]
[115 168 437]
[238 269 286 381 412 414

[225 340 385 437 452 475 527 559 590 591]
[ 78 153 268 544 585 592]
[ 31 342 385 396 406 428 449 484 485 500]
[ 72 216 427 443 475 479 516 517 593]
[224 425 500 507 526 560]
[236 393 406 443 447 505 509 521 581]
[ 14  75 164 179 258 279 427 442 500 553]
[ 64 133 148 303 357 363 366 480 503 540 564]
[ 68 109 149 250 347 362]
[ 80  99 168 313 314 404 480 578]
[340 412 420 433 503 506 538 552 566 576]
[ 35 106 166 259 347 415 457 464 536]
[173 252 383 454 467 522]
[ 70  79  97 143 358 496 527 585]
[  6  23 219 433 531 551 578]
[ 22  88 137 354 378 468 533 614 615]
[ 98 273 344]
[52]
[ 81 258 350 420 501]
[462 477 491 496 524 586]
[  1 209 372 452 570]
[  8  72  93 141 191 421 490 511 536]
[116 420 436 478 530 556]
[ 70 143 385 431 477 496]
[373 399 422 478]
[419]
[170 370 374 394 494 529 556 560 584]
[159 240 258 358 365 382 416 421 428 431 436 479 482 524 528 538 602 608]
[153 369 384 395 463 519 525 526 543 557 579 600]
[ 72  85 143 204 344 358 370 391 439 453 528 536 547]
[ 49 160 363 

[384 416 417 461 560 579]
[257 344 387]
[ 43  73 121 202 409 450 468 517 552 564 571 575 576]
[356 461 563 572]
[ 40 233 364 369 370 419 450 463 576]
[143 349 366 384 405 495 496 504 521 527 567 596]
[357 435 473 517 551 552 566 576]
[ 88 406 577]
[ 18 192 210 411 421 484 529 552 576 580 597]
[392 402 493 508]
[ 92 411 413 453 455 521 568]
[208 261 385 408 478 524 530 559 607]
[ 21 111 238 258 266 300 302 369 374 380 399 526 544 557 602]
[ 69 269 308 395 411 556 591]
[137 172 358 399 419 421 431 455 462 482 501 508]
[ 62 127 160 182 200 222 236 313 368 372 381 382 414 428 444 496 511]
[ 49 143 383 460 506]
[392 417 470 498 560 562]
[213 379 405 411 415 420 566]
[136 211 388 394 406 416 468 471 530 583]
[ 40 340 359 365 392 439 576]
[ 21  32 269 374 414 461 496 572]
[238 412 431 437 524 528 573]
[ 83 372 399 487 567]
[191 381 385 392 394 439 493 517 519]
[181 258 308 361 414 421 564 591]
[ 21 365 375 417]
[216 382 462 598]
[222 381 385 419 439 517 580 597]
[191 280 388 392 395 398 414 4

[188 353 434 441 465 492 527 563 572 581]
[ 84 152 233 346 378 388 405 568]
[ 52 110 118 354 481 527 551 559 569 579]
[161 222 355 375 378 476 522 534 549 584 614 615]
[478 485]
[346 353 404 431 497 498 552 565 581]
[173 243 481 522 541 572 579]
[ 52 395 551]
[  6  81 378 436 439 440 465 563 564 615]
[ 22 137 497 614]
[244 353 417 493 566]
[  1  74  98 144]
[ 34 366 434 487 544 569 572 582]
[ 24  43  55 214 236 280 405 483 615]
[ 80 118 354 584 599]
[350 351 498 502 578 614]
[290 518 544 555]
[  1 110 352 534 541 559 615]
[417 491 565 572 579]
[469 470 481 485 549 566 588 615]
[404 417 434 466 569 589]
[ 68 405 438 465 493 551 572 580 614]
[196 217 390 459 469 495 525 565]
[  9  22 178 363 375 492 599 615]
[ 12  24  84 354 383 459 512 550 614]
[  7  43  80 118 465 469 615]
[392]
[  4  81 232 280 409 421 572 614 615]
[222 458]
[ 74 110 295 409 439 440 446 457 518 560]
[  1  18 350 352 462 483]
[ 77 178 375 379 388 443 451 519 594 614 615]
[219 410 560]
[ 84 171 212 260 275 381 392 414 4

[198 343 403 406 424 451 456 484]
[ 11 136 261 464 559]
[269 362 463 501 514 518 519 527 531 545 557 564 574 587 594]
[  7 119 238 515 546]
[383 403 416 451 454 510 529 596]
[341 345 394 417 458 460 471 590]
[ 11  32  54 362 364 406 408 424 426 516 544]
[379 380 463 596]
[ 39 172 230 376 457 524 597]
[ 85 472 477 496 559]
[364 428 455 544 608]
[ 74 185 257 262 397 415 417 471 488]
[429 436 453 475 561 571 589]
[ 11 471 478 510]
[161 385 408 437]
[172 515 540 541 570]
[ 37 194 357 437 458]
[  7 106 165 167 203 218 403 457 475 484 522 559]
[148 379 417 506 510 525 594]
[ 11 119 134 162 197 224 238 561 590]
[403 409 470 479 495 506 508 580 591]
[145 193 260 379 434 436 513 519]
[185 341 361 388 456 529 546 564 616]
[243 343 373 403 473 477]
[ 38 257 361 383 440 475 483 544]
[ 57 123 268 269 406 479 495 526]
[373 415 445 467 490 510]
[468 560 572 583 616]
[192 436 462 471 477 488 495]
[ 15  84 173 350 383 417 458 483 551 552]
[145 387 421 482 588]
[198 286 468]
[ 55 197 409 484 485 488 511

[158 179 349 484 529]
[ 11 123 216 352 357 366 417 445 447 480 550]
[ 46  92 136 257 274 461 485]
[106 406 583]
[ 17 206 224 415 431 477 490 508 544]
[ 54  74 344 374 417 467 483 484 537]
[ 32  61 369 407 413 439 462 491 508]
[181 350 398 434 496 570 575]
[158 290 403 461 477 490 518 530 538]
[349 375 379 394 431 451 516 547]
[301 471]
[ 98 240 364 387 394 408 437 484 495 517 559 560 583]
[ 74  79 178 343 379 385 445 512 524]
[101 471 475 526 586]
[206 260 594]
[123 224 343 451 529]
[ 13  32 165 369 383 424 458 463 588]
[347]
[ 54 161 364 419 422 429 471 490 509 580 587]
[197 391 421 456 496 529]
[346 431 436 476 477 478 486 520 524 579]
[156 236 326 385 542 560]
[ 72 121 422 455 478 493 496 501 521 607]
[384 395 402 421 428 520 523 528 599]
[ 53  62 147 260 269 358 399 448 487 496 521 530 531 542 549 579]
[ 36  69 212 221 417 473 543 572 577]
[ 84 287 354 381 392 398 414 468 484 520 526 569 582]
[ 55 493 496 542]
[237 385 478]
[ 33  61  81 106 147 560 600]
[355 562]
[ 34  77 267 283 3

[168 184 366 405 512 520 560 566 582 604]
[ 71 144 349 402 417 502 510 525 552]
[233 391 404 430 498 527 550 579]
[ 36 121 152 299 517 520 523 561]
[  8 103 210 231 420 495 496 521]
[ 35  56  90 232 368 414 422 431]
[ 21  55 143 154 246 308 374 382 385 402 421 436 439 478 482 501 542 547]
[ 62 101 106 236 269 303 358 375 395 398 399 422 469 481 543 588]
[ 81 147 159 172 180 212 368 419 428 473 490 524 559]
[127 200 260 355 370 381 414 420 497]
[ 72 348 352 392 398 439 502 519]
[ 73 243 351 369 375 412 436 464 536 538 546 573]
[ 63 178 349 367 376 394 413 451 508 516 537]
[ 13 344 573]
[132 274 356 364 579]
[ 32  95 101 350 352 551 555]
[ 21 316 398 400 404 480 516 569 583]
[ 90 351 385]
[349 362 369 383 431 433 434 474 476 484 508 513 538 557]
[ 63 132 153 193 256 356 360 384 423 424 451 537]
[379 385 403 458 461 507 513]
[ 72 290 362 454 465 505 588 596]
[185 217 341 360 364 365 369 384 463 527]
[ 13  92 121 191 312 343 349 379 383 407 416 422 471 490 516 587]
[352 417]
[ 32 350 454 4

[ 43  74  79 110 232 418 459 555 560]
[ 41 417 430 492 566 572]
[ 68 428 469 481 565]
[  3  81 108 311 346 516]
[ 84 142 189 308 497]
[ 52 210 351 480 492 552]
[203 386 417 443 482 506 516 535 541]
[ 18  76 112 122 171 375 434 446 589]
[239 352 365 388 392 416 420 440 444 457 484 575]
[ 63 163 219 231 290 340 454 461 470 504 594]
[ 29 178 444]
[ 41 182 350 356 398 480]
[312 334 421 507 508 546 552 579]
[488 526 573 597]
[ 60 377 438 466]
[ 68 144 197 373 422 455 480 543 560 592]
[ 35 193 261 418 467 487]
[212 238 268 397 399 494 525 531 555 601]
[  7  41  43  84 173 266 269 526]
[111 437 443 459 509 551 565]
[ 74 351 405 428 469 559 576 598]
[531 535 552]
[494 499 515 565 598 604]
[134 174 206 384 481 487 569 572 578 579 610]
[ 68 125 210 250 386 405 441 552 581]
[233 379 416 451 484 529]
[353 436 565 566 583]
[ 52  81 108 138 189 346 438 481 492 543 572]
[193 231 439 441 469 551]
[ 70 368 377 378 424 428 526 533 536 546]
[ 45 326 353 457 518 535 544]
[ 22 236 437 492 521 552]
[134 192

[119 308 374 496 506 517 536 563]
[178 375 381 392 414 431 439 455 484 503 582]
[247 355 372 420 460 517 540 588]
[ 73 125 191 398 475 525 534]
[ 18 357 377 381 392 414 421 439 453 470]
[149 267 367 446 506 570]
[121 373 402 437 477 482 533 557]
[181 367 372 421 518 520]
[ 62 141 283 364 375 431 448 493 496]
[106 178 222 370 385 391 399 419 428 477 478 482 492 501 528 579]
[436 542]
[147 199 384 399 416 428 431 439 453 482 494 519 520 530 543 556 581 585]
[119 212 221 269 358 368 421 473 521 529 559]
[ 37 143 391 435 439 542]
[121 236 355 381 392 412 414 420 437 462 490 563]
[127 232 410 438 493 534 557]
[ 33 178 368 385 398 404 412 475 478 523]
[ 72 452 508 543 585]
[366 370 376 385 412 493 501 557]
[358 399 428 432 526]
[147 172 212 303 351 364 368 374 391 419 491 579 588]
[106 200 381 388 392 414 439 460 496 539 557]
[ 56 127 396 398 406 412 425 452 486 503 516]
[ 31  78 105 342 360 370 449 463 479 544 569]
[148 223 243 261 364 366 406 437 451 500]
[ 14 216 278 367 376 404 436 521 5

[207 219 385 424 519 571]
[ 25 134 260 364 374 423 452 500 601]
[166 210 371 477 526 579]
[103 182 198 370 577]
[191 269 360 462]
[308 364 370 385 399 416 437 540]
[  5  86 212 371 428 478 496 520]
[370 398 447 452 516 541]
[412 585]
[374 396 406 425 437 443 449 480 485 499 509 564 571 590]
[115 305 361 397 479 500 507 521 579]
[ 11  36 128 216 342 366 367 443 484 508 544]
[55]
[258 347 425 427 494 500 507 509 521 579]
[ 50 151 400 475 479 537]
[ 75 367 402 406 427 443 447 500 526 572 579 593]
[ 14 164 250 256 384 393 481]
[ 28  64 111 148 212 247 308 325 327 363 367 457 480 494 564]
[ 23  84 175 187 215 240 269 275 300 420 447 462]
[149 232 243 503 517 561]
[ 56 166 347 372 423 508 511 538 552 574]
[133 263 344 408 413 416 436 461 464 467 473 484 513 584]
[ 79 374 383 429 433 547 575]
[ 54 236 340 461 490 544 585]
[179 348 354 373 456 473]
[ 55 350 369 416 460 599]
[343 430 464 547]
[403 446 455 480 508 537]
[ 18  21 151 398 516 591]
[374 387 416 434 454]
[ 87 103 131 207 251 464 485 

[440 528 553 558 566 577]
[350 475 480]
[206 346 419 492 541 552 553 558 599]
[264 301 423 498 544]
[497 551]
[354 366 378 417 429 535 572]
[ 23 367 374 413 473 484 500 521 585]
[350 404 430 480 578]
[384 420 483 533 553 559]
[386 538 615]
[481 506 614]
[ 26  52 486 526 561]
[  6  46 420 497 525 527 583]
[210 585]
[ 34  55 347 417 452 462 552]
[  5   8  48 149 372 374 385 392 420 430 443 457 468 487 534 536 549]
[143 225 383 395 413 439 461 519 560]
[ 45  62 369 394 412 416 421 464 484 544 575]
[ 63  95 192 193 212 246 269 276 312 356 377 380 439 488]
[176 545]
[ 41 389 462]
[ 21 125 371 533]
[102 191 224 361 411 517 564]
[141 214 231 387 440 484 527 576 605]
[396 422 437 487 585]
[ 63 143 385 389 420 431 453 462 524 528 536 549 578]
[  8  21 225 238 436 461 490 534]
[18]
[525 561 585]
[173 419 478 533 566]
[ 52 258 391 423 524 535 569 582]
[  6  70 232 340 370 373 392 420 453 528 549 599]
[374 377 439]
[ 18 181 212 246 359 393 473 607]
[238 464 520 560 585]
[ 21 125 143 160 347 384 38

[ 77 229 283 352 358 374 394 439 495 501 557]
[ 19  21  89 147 354 383 385 410 469 493 500 560]
[ 78 431 445 534]
[164 254 395 404 415 471 484 492 519 563 577 587]
[378 412 453 456 556 559]
[161 165 173 194 369 473 524 532]
[345 509 559]
[267 378 381 392 414 420 533 582]
[  6  45 187 394 395 412 422 478 519]
[385 428 501 531 536 543]
[ 21  38 286 376 399 419 471 476 478 493 508]
[358 377 404 473 492 520 542]
[ 95 212 370 390 399 452 494 526 556 572]
[ 37  69 428 473 524]
[ 91 180 237 240 386 469 528]
[229 361 370 378 381 392 395 414 445 451 534 586]
[ 31  77 209 415 437 439 518]
[ 72 187 380 412 421 478 508 529]
[ 21 303 374 385 399 428 556 578]
[ 37 223 434 460 501 563]
[ 61  80  95 173 498 582]
[ 77 205 379 381 392 453 518 532]
[376 394 557]
[ 19 157 347 379 384 431 445 453 484 495 555]
[ 21  45  89 345 478 482 494 501 517]
[358 377 378 385 399 456 469 473 481 543]
[ 69  81 429 492 528 533]
[ 77 404 405 555 572 615]
[145 187 386 416 592]
[ 89 203 395 398 493 501 570]
[165 209 382 518

In [214]:
i = 0
size = 0
for event in eventsInFramesGUI:
    size += event.size
    if event.size == 0:
        i += 1

In [47]:
i

4

In [221]:
#save to matfile
mdic = {'eventsForFilters': eventsForFiltersGUI,
'eventsInFrames':  eventsInFramesGUI,
'filterCentroids': filterCentroidsGUI,
'filtersBinary': filtersBinaryGUI}
scipy.io.savemat("data_packed_for_generation_synth_GT.mat", mdic)

In [139]:
my_data = scipy.io.loadmat("data_packed_for_generation_synth.mat")
events = my_data['eventsForFilters']

In [140]:
events[0][0]

array([[628]])

In [222]:
[a1, a2, a3, a4] = load_ground_truth_generation_data("data_packed_for_generation_synth_GT.mat", gui=True)

336


/home/user/anaconda3/envs/hdf5/lib/python3.7/site-packages/ipykernel_launcher.py:62: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
/home/user/anaconda3/envs/hdf5/lib/python3.7/site-packages/ipykernel_launcher.py:84: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray


In [206]:
[b1, b2, b3, b4] = load_ground_truth_generation_data("/home/user/Documents/single_session/dataPackedForGeneration.mat", gui=False)

/home/user/anaconda3/envs/hdf5/lib/python3.7/site-packages/ipykernel_launcher.py:50: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
/home/user/anaconda3/envs/hdf5/lib/python3.7/site-packages/ipykernel_launcher.py:72: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray


In [229]:
a4

array([array([], dtype=float64),
       array([ 61,  92, 205, 387, 489, 503, 592], dtype=uint16),
       array([224, 388, 429, 476], dtype=uint16), ...,
       array([ 67, 410, 448, 525, 561, 563], dtype=uint16),
       array([380, 384, 385, 419, 431, 445, 498, 508], dtype=uint16),
       array([], dtype=float64)], dtype=object)

In [230]:
b4

array([array([], dtype=float64), array([157, 218, 414], dtype=uint16),
       array([281, 370, 441], dtype=uint16), ...,
       array([170], dtype=uint8), array([], dtype=float64),
       array([], dtype=float64)], dtype=object)

In [337]:
events_in_this_frame = a4[1]
events_in_this_frame.shape
#a1[events_in_this_frame][0].shape

(1, 1)

In [338]:
events_in_this_frame = b4[1]
events_in_this_frame.shape
#b1[events_in_this_frame][0].shape

(3,)

In [23]:
i = 0
size = 0
for event in a4:
    size += event.size
    if event.size == 0:
        i += 1

In [20]:
size

49213